#! /bin/bash
#
#   Run selftests and check memory

#   Valgrind command
VG="valgrind --tool=memcheck --leak-check=full --show-reachable=yes --suppressions=valgrind.supp"

gcc -g -o hello_zproto_selftest hello_zproto*.c ${CFLAGS} ${LDFLAGS} -DHAVE_CONFIG_H -lczmq -lzmq -luuid -lsodium

if [ $? -eq 0 ]; then
    if [ "$1" == "-q" ]; then
        ./hello_zproto_selftest
        exit
    else
        $VG ./hello_zproto_selftest
    fi
fi
rm -f vgcore.*

